/** @type {import('tailwindcss').Config} */
import daisyui from "daisyui"
export default {
  content: ["./findBookCafe/**/*.{html,js}", "./landingPage/**/*.{html,js}"],
  daisyui: {
    themes: ["retro", ],
  },
  themes: [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
  ],
  plugins: [daisyui],
}
  