# Generated by Django 4.2.15 on 2024-10-07 19:50

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
