# Generated by Django 4.0.6 on 2022-07-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeType',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findBookCafe.city')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('website', models.URLField(max_length=300)),
                ('facebook', models.URLField(max_length=300)),
                ('instagram', models.URLField(max_length=300)),
                ('tripadvisor', models.URLField(max_length=300)),
                ('googleMaps', models.URLField(max_length=300)),
                ('isBookShop', models.BooleanField()),
                ('isCoffeeAllowed', models.BooleanField(default=True)),
                ('hasLunch', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findBookCafe.city')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findBookCafe.region')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findBookCafe.cafetype')),
            ],
        ),
    ]
