# Generated by Django 4.1 on 2023-02-09 10:57

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name_en', models.CharField(default=models.CharField(max_length=200, primary_key=True, serialize=False), max_length=200)),
                ('slug', models.CharField(default=models.CharField(default=models.CharField(max_length=200, primary_key=True, serialize=False), max_length=200), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name_en', models.CharField(default=models.CharField(max_length=200, primary_key=True, serialize=False), max_length=200)),
                ('slug', models.CharField(default=models.CharField(default=models.CharField(max_length=200, primary_key=True, serialize=False), max_length=200), max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findBookCafe.city')),
            ],
        ),
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('content', django_quill.fields.QuillField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CAF', 'Καφετέρια'), ('LIB', 'Βιβλιοθήκη')], default=('CAF', 'Καφετέρια'), max_length=3)),
                ('thumbnail', models.ImageField(null=True, upload_to='uploads/')),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(default=models.CharField(max_length=300), max_length=300)),
                ('slug', models.CharField(default=models.CharField(default=models.CharField(max_length=300), max_length=300), max_length=300)),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('facebook', models.URLField(blank=True, max_length=300)),
                ('instagram', models.URLField(blank=True, max_length=300)),
                ('tripadvisor', models.URLField(blank=True, max_length=300)),
                ('googleMaps', models.URLField(blank=True, max_length=300)),
                ('isBookShop', models.BooleanField()),
                ('isAccessibleForPeopleWithDisabilities', models.BooleanField(default=False)),
                ('isCoffeeAllowed', models.BooleanField(default=True)),
                ('hasLunch', models.BooleanField(default=False)),
                ('internetQuality', models.CharField(choices=[('0', 'none'), ('1', 'bad'), ('2', 'normal'), ('3', 'good')], default=('2', 'normal'), max_length=1)),
                ('powerOutlets', models.CharField(choices=[('0', 'none'), ('1', 'few'), ('2', 'normal'), ('3', 'many'), ('4', 'is everywhere')], default=('2', 'normal'), max_length=1)),
                ('description', django_quill.fields.QuillField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findBookCafe.region')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', django_quill.fields.QuillField()),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='uploads/')),
                ('shops', models.ManyToManyField(to='findBookCafe.shop')),
            ],
        ),
    ]
