# Generated by Django 4.0.6 on 2022-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.AutoField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
