# Generated by Django 4.0.6 on 2022-08-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0006_alter_cafetype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('CAF', 'Καφετέρια'), ('LIB', 'Βιβλιοθήκη')], default=('CAF', 'Καφετέρια'), max_length=3),
        ),
        migrations.DeleteModel(
            name='CafeType',
        ),
    ]
