# Generated by Django 4.0.6 on 2022-08-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0008_shop_internetquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='powerOutlets',
            field=models.CharField(choices=[('0', 'none'), ('1', 'few'), ('2', 'normal'), ('3', 'many'), ('4', 'is everywhere')], default=('2', 'normal'), max_length=1),
        ),
        migrations.AlterField(
            model_name='shop',
            name='internetQuality',
            field=models.CharField(choices=[('0', 'none'), ('1', 'bad'), ('2', 'normal'), ('3', 'good')], default=('2', 'normal'), max_length=1),
        ),
    ]
