# Generated by Django 4.0.6 on 2022-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0009_shop_poweroutlets_alter_shop_internetquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Thumbnail',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
