# Generated by Django 4.0.6 on 2022-08-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0010_shop_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='Thumbnail',
            new_name='thumbnail',
        ),
    ]
