# Generated by Django 4.1 on 2022-08-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0011_rename_thumbnail_shop_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
    ]
