# Generated by Django 4.0.6 on 2022-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0013_simplepage_city_name_en_city_slug_region_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='slug',
            field=models.CharField(default='/static', max_length=300, unique=True),
        ),
    ]
