# Generated by Django 4.0.6 on 2022-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0014_simplepage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepage',
            name='slug',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
