# Generated by Django 5.1.1 on 2024-09-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0016_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='order_position',
            field=models.IntegerField(default=0),
        ),
    ]
