# Generated by Django 4.2.5 on 2024-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0017_shop_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='order_position',
            field=models.IntegerField(default=0),
        ),
    ]
