# Generated by Django 4.2.5 on 2024-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findBookCafe', '0019_alter_collection_order_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order_position']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['order_position']},
        ),
        migrations.AlterField(
            model_name='collection',
            name='order_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='order_position',
            field=models.IntegerField(default=0),
        ),
    ]
